
## - General info:

-> https://www.linkedin.com/groups/4243277

http://www.initc3.org/publications.html

http://www.meetup.com/IC3-NYC-Blockchain-Meetup/events/231588722

http://www.meetup.com/IC3-NYC-Blockchain-Meetup/

https://nadim.computer/

http://blockchain.media.mit.edu/syllabus.html

http://ledgerjournal.org/ojs/index.php/ledger/index

https://blog.sldx.com/

http://www.michaelnielsen.org/ddi/how-the-bitcoin-protocol-actually-works/

## - Enigma / MIT:

"Run Code On Encrypted Data - Secure data & protect privacy without compromising functionality”

http://enigma.media.mit.edu/

http://enigma.media.mit.edu/enigma_full.pdf

https://www.wired.com/2015/06/mits-bitcoin-inspired-enigma-lets-computers-mine-encrypted-data/

Bob McElrath explains some aspects, like the multi-party-computation:

https://www.youtube.com/watch?v=Z4K_Rn8QWGo



## - Mics / Resources:
 

https://www.meetup.com/BitcoinWednesday/events/227452108/

https://www.youtube.com/channel/UCt-Po2gFQxiUngwJXh6s04w/videos 

http://www.bitcoinwednesday.com/profile-alexander-vasylchenko-of-grid-singularity/ 

http://gridsingularity.com/#/0/1

http://www.slideshare.net/ericcattoir/anatomy-of-a-hyperledger-application?qid=f786f22c-657b-406f-b66b-12029b692757&v=&b=&from_search=1 

https://www.youtube.com/watch?v=pNerM72f0Pk 

https://github.com/Azure/azure-blockchain-projects/blob/master/bletchley/bletchley-whitepaper.md 

http://www.slideshare.net/splix/ethereum-classic-roadmap?qid=33bfdf62-8669-4a8c-a37e-f9ab66993a1f&v=&b=&from_search=1 

https://github.com/HydraChain/hydrachain 

https://openzeppelin.org/ 

https://drive.google.com/file/d/0B42vMkapQi1MSEVaa2tuVEtXZXM/view

http://tinyletter.com/datamachina/letters/data-machina-y3-week-34 

http://www.slideshare.net/ormium/architecture-of-the-hyperledger-blockchain-fabric-christian-cachin-ibm-research-zurich 

https://github.com/jpmorganchase/quorum 

http://www.slideshare.net/TobiasDisse/alternative-consensus-enterprise-blockchain-66788582?qid=0cbed771-c556-4db9-8fd2-f7bd9f712afa&v=&b=&from_search=9

http://www.coinspeaker.com/2016/11/30/royal-mint-partners-with-cme-group-to-offer-gold-trading-based-on-blockchain/ 

http://www.telegraph.co.uk/business/2016/11/29/royal-mint-offers-gold-trading-based-blockchain/ 

https://medium.com/@bergealex4/the-artificial-block-size-limit-1b69aa5d9d4#.5slogz3ye 

https://medium.com/@bergealex4






# Analysing the BTC BC

https://www.youtube.com/watch?v=FjScBC3X--U


Analysis of Bitcoin Transaction Flows to Reveal Usage and Geographic Patterns

http://www.nicolascourtois.com/bitcoin/Bitcoin%20Thesis%20ACM_Bissesar_Shiva.pdf

Who Uses Bitcoin? An exploration of the Bitcoin community

http://ieeexplore.ieee.org/abstract/document/6890928/


Characteristics of Bitcoin users: an analysis of Google search data

("[...] four possible clientele: computer programming enthusiasts, speculative investors, Libertarians and criminals. Computer programming and illegal activity search terms are positively correlated with Bitcoin interest, while Libertarian and investment terms are not.")

http://www.tandfonline.com/doi/abs/10.1080/13504851.2014.995359


Analyzing the Bitcoin Network: The First Four Years

("Our analyses reveal the major Bitcoin businesses and markets. Our results also give insights on the business distribution by countries and how businesses evolve over time.")

http://www.mdpi.com/1999-5903/8/1/7


Evaluating User Privacy in Bitcoin

https://link.springer.com/chapter/10.1007/978-3-642-39884-1_4


An Analysis of Anonymity in the Bitcoin System

https://link.springer.com/chapter/10.1007/978-1-4614-4139-7_10





