

# General / overviews:

- Hacking Blockchain https://www.youtube.com/watch?v=0gL6DsR6vGg
- Security Implications of Non-Financial Uses of Blockchain Technology  https://www.youtube.com/watch?v=fEA398SELOE
- Ethereum: The Good, The Bad, The Ugly https://www.youtube.com/watch?v=BwPulJKP1_Y
- POS https://medium.com/@pirapira/formal-methods-on-some-pos-stuff-e309775c2ab8#.e809zttpx
- APJ Quick Look: Security Implications of Using Blockchain Technology for More than Money https://www.youtube.com/watch?v=dGGnHTnkSCs
- SoK: Research Perspectives and Challenges for Bitcoin and Cryptocurrencies:
- https://www.youtube.com/watch?v=ZL0TbjSrwAI
- http://www.jbonneau.com/doc/BMCNKF15-IEEESP-bitcoin.pdf 
- News on BTC scams: https://cointelegraph.com/tags/bitcoin-scams
- Hard forks and the block size debate: https://medium.com/@sdaftuar/how-the-bitcoin-experiment-might-fail-7f6c24f99ecf#.u7m7rxf15

# Anonymity

- Anonymity in Bitcoin? – The Users’ Perspective http://aisel.aisnet.org/icis2016/Crowdsourcing/Presentations/10/
- Also see: https://github.com/mirelacc/blockchian_related/blob/master/finance_and_blockcain.Rmd
- "As more people earn income in Blockchain-based currency the social norm of salary confidentiality is challenged." https://cointelegraph.com/news/full-disclosure-of-your-salary-blockchain-remuneration-models

# Mining & power

- Majority Is Not Enough: Bitcoin Mining Is Vulnerable https://link.springer.com/chapter/10.1007/978-3-662-45472-5_28
- http://www.newsbtc.com/2016/10/17/bitcoin-miners-china-may-getting-much-control/

# Known hacks:

- Hijacking Bitcoin: Large-scale Network Attacks on Cryptocurrencies https://arxiv.org/pdf/1605.07524.pdf
- Attacks on hashes: https://z.cash/technology/history-of-hash-function-attacks.html
- http://www.coindesk.com/bitfinex-shuts-down-customer-bitcoin-stolen/
- https://www.cryptocoinsnews.com/hackers-steal-millions-in-bitcoin-with-phone-numbers/
- https://letstalkbitcoin.com/is-bitcoin-overpaying-for-false-security
- Dissecting Ponzi schemes on Ethereum: identification, analysis, and impact https://arxiv.org/pdf/1703.03779.pdf
- & http://libertarianstandard.com/2013/12/01/ponzi-logic-debunking-gary-north/

# Scalability

Congestion in BTC:

- Transaction cap: 5-7 tx/sec. - 12.5, and 1 MB/ 10 min.
- 
- https://www.oreilly.com/ideas/blockchain-scalability
- http://www.coindesk.com/bitfury-flare-lightning-network-routing/
- https://www.bigchaindb.com/whitepaper 
- https://www.cryptocoinsnews.com/ethereum-announces-unlimited-scalability-roadmap

# Other

- “When perhaps the real problem is money itself!”: the practical materiality of Bitcoin http://www.tandfonline.com/doi/abs/10.1080/10350330.2013.777594


# Attempts of solving issues:

- Layers on top of bitcoin may be a solution, 'layer 2 services' like: Side-chains (https://blockstream.com/sidechains.pdf) 
- or the Lightning Network, "Scalable, Instant Bitcoin/Blockchain Transactions" https://lightning.network/
 
Ethereum:

- https://ethereumfoundation.org/devcon/?session=14-the-mauve-revolution
- https://www.youtube.com/watch?v=bSdwqa3Yl0Q
- Ethereum progress: https://www.youtube.com/watch?v=irHtY3t0IHY

Anonymity, ZKP's & zsnarks:

- https://en.wikipedia.org/wiki/Zerocoin 
- https://en.wikipedia.org/wiki/Zcash
- https://www.youtube.com/watch?v=1GTRfZ0m7M8
- https://www.youtube.com/watch?v=S6qOj9ap6RM
- https://en.wikipedia.org/wiki/Non-interactive_zero-knowledge_proof

IPFS:

- https://www.youtube.com/watch?v=ewpIi1y_KDc
- https://www.youtube.com/watch?v=jONZtXMu03w
- https://www.youtube.com/watch?v=cU-n_m-snxQ


